/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatusRouteImport } from './routes/status'
import { Route as OtaBlockerRouteImport } from './routes/ota-blocker'
import { Route as LatestDotjsonRouteImport } from './routes/latest[.]json'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegisterTypeRouteImport } from './routes/register.$type'
import { Route as ApiPublicSettingsRouteImport } from './routes/api/public/settings'
import { Route as ApiPublicRegistrationStatusRouteImport } from './routes/api/public/registration-status'
import { Route as ApiPublicNowpaymentsWebhookRouteImport } from './routes/api/public/nowpayments-webhook'
import { Route as ApiAdminSettingsRouteImport } from './routes/api/admin/settings'
import { Route as ApiAdminSessionRouteImport } from './routes/api/admin/session'
import { Route as ApiAdminRegistrationsRouteImport } from './routes/api/admin/registrations'

const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const OtaBlockerRoute = OtaBlockerRouteImport.update({
  id: '/ota-blocker',
  path: '/ota-blocker',
  getParentRoute: () => rootRouteImport,
} as any)
const LatestDotjsonRoute = LatestDotjsonRouteImport.update({
  id: '/latest.json',
  path: '/latest.json',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterTypeRoute = RegisterTypeRouteImport.update({
  id: '/register/$type',
  path: '/register/$type',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSettingsRoute = ApiPublicSettingsRouteImport.update({
  id: '/api/public/settings',
  path: '/api/public/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRegistrationStatusRoute =
  ApiPublicRegistrationStatusRouteImport.update({
    id: '/api/public/registration-status',
    path: '/api/public/registration-status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicNowpaymentsWebhookRoute =
  ApiPublicNowpaymentsWebhookRouteImport.update({
    id: '/api/public/nowpayments-webhook',
    path: '/api/public/nowpayments-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminSettingsRoute = ApiAdminSettingsRouteImport.update({
  id: '/api/admin/settings',
  path: '/api/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSessionRoute = ApiAdminSessionRouteImport.update({
  id: '/api/admin/session',
  path: '/api/admin/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminRegistrationsRoute = ApiAdminRegistrationsRouteImport.update({
  id: '/api/admin/registrations',
  path: '/api/admin/registrations',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/latest.json': typeof LatestDotjsonRoute
  '/ota-blocker': typeof OtaBlockerRoute
  '/status': typeof StatusRoute
  '/register/$type': typeof RegisterTypeRoute
  '/api/admin/registrations': typeof ApiAdminRegistrationsRoute
  '/api/admin/session': typeof ApiAdminSessionRoute
  '/api/admin/settings': typeof ApiAdminSettingsRoute
  '/api/public/nowpayments-webhook': typeof ApiPublicNowpaymentsWebhookRoute
  '/api/public/registration-status': typeof ApiPublicRegistrationStatusRoute
  '/api/public/settings': typeof ApiPublicSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/latest.json': typeof LatestDotjsonRoute
  '/ota-blocker': typeof OtaBlockerRoute
  '/status': typeof StatusRoute
  '/register/$type': typeof RegisterTypeRoute
  '/api/admin/registrations': typeof ApiAdminRegistrationsRoute
  '/api/admin/session': typeof ApiAdminSessionRoute
  '/api/admin/settings': typeof ApiAdminSettingsRoute
  '/api/public/nowpayments-webhook': typeof ApiPublicNowpaymentsWebhookRoute
  '/api/public/registration-status': typeof ApiPublicRegistrationStatusRoute
  '/api/public/settings': typeof ApiPublicSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/latest.json': typeof LatestDotjsonRoute
  '/ota-blocker': typeof OtaBlockerRoute
  '/status': typeof StatusRoute
  '/register/$type': typeof RegisterTypeRoute
  '/api/admin/registrations': typeof ApiAdminRegistrationsRoute
  '/api/admin/session': typeof ApiAdminSessionRoute
  '/api/admin/settings': typeof ApiAdminSettingsRoute
  '/api/public/nowpayments-webhook': typeof ApiPublicNowpaymentsWebhookRoute
  '/api/public/registration-status': typeof ApiPublicRegistrationStatusRoute
  '/api/public/settings': typeof ApiPublicSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/latest.json'
    | '/ota-blocker'
    | '/status'
    | '/register/$type'
    | '/api/admin/registrations'
    | '/api/admin/session'
    | '/api/admin/settings'
    | '/api/public/nowpayments-webhook'
    | '/api/public/registration-status'
    | '/api/public/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/latest.json'
    | '/ota-blocker'
    | '/status'
    | '/register/$type'
    | '/api/admin/registrations'
    | '/api/admin/session'
    | '/api/admin/settings'
    | '/api/public/nowpayments-webhook'
    | '/api/public/registration-status'
    | '/api/public/settings'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/latest.json'
    | '/ota-blocker'
    | '/status'
    | '/register/$type'
    | '/api/admin/registrations'
    | '/api/admin/session'
    | '/api/admin/settings'
    | '/api/public/nowpayments-webhook'
    | '/api/public/registration-status'
    | '/api/public/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  LatestDotjsonRoute: typeof LatestDotjsonRoute
  OtaBlockerRoute: typeof OtaBlockerRoute
  StatusRoute: typeof StatusRoute
  RegisterTypeRoute: typeof RegisterTypeRoute
  ApiAdminRegistrationsRoute: typeof ApiAdminRegistrationsRoute
  ApiAdminSessionRoute: typeof ApiAdminSessionRoute
  ApiAdminSettingsRoute: typeof ApiAdminSettingsRoute
  ApiPublicNowpaymentsWebhookRoute: typeof ApiPublicNowpaymentsWebhookRoute
  ApiPublicRegistrationStatusRoute: typeof ApiPublicRegistrationStatusRoute
  ApiPublicSettingsRoute: typeof ApiPublicSettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ota-blocker': {
      id: '/ota-blocker'
      path: '/ota-blocker'
      fullPath: '/ota-blocker'
      preLoaderRoute: typeof OtaBlockerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/latest.json': {
      id: '/latest.json'
      path: '/latest.json'
      fullPath: '/latest.json'
      preLoaderRoute: typeof LatestDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/$type': {
      id: '/register/$type'
      path: '/register/$type'
      fullPath: '/register/$type'
      preLoaderRoute: typeof RegisterTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/settings': {
      id: '/api/public/settings'
      path: '/api/public/settings'
      fullPath: '/api/public/settings'
      preLoaderRoute: typeof ApiPublicSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/registration-status': {
      id: '/api/public/registration-status'
      path: '/api/public/registration-status'
      fullPath: '/api/public/registration-status'
      preLoaderRoute: typeof ApiPublicRegistrationStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/nowpayments-webhook': {
      id: '/api/public/nowpayments-webhook'
      path: '/api/public/nowpayments-webhook'
      fullPath: '/api/public/nowpayments-webhook'
      preLoaderRoute: typeof ApiPublicNowpaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/settings': {
      id: '/api/admin/settings'
      path: '/api/admin/settings'
      fullPath: '/api/admin/settings'
      preLoaderRoute: typeof ApiAdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/session': {
      id: '/api/admin/session'
      path: '/api/admin/session'
      fullPath: '/api/admin/session'
      preLoaderRoute: typeof ApiAdminSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/registrations': {
      id: '/api/admin/registrations'
      path: '/api/admin/registrations'
      fullPath: '/api/admin/registrations'
      preLoaderRoute: typeof ApiAdminRegistrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  LatestDotjsonRoute: LatestDotjsonRoute,
  OtaBlockerRoute: OtaBlockerRoute,
  StatusRoute: StatusRoute,
  RegisterTypeRoute: RegisterTypeRoute,
  ApiAdminRegistrationsRoute: ApiAdminRegistrationsRoute,
  ApiAdminSessionRoute: ApiAdminSessionRoute,
  ApiAdminSettingsRoute: ApiAdminSettingsRoute,
  ApiPublicNowpaymentsWebhookRoute: ApiPublicNowpaymentsWebhookRoute,
  ApiPublicRegistrationStatusRoute: ApiPublicRegistrationStatusRoute,
  ApiPublicSettingsRoute: ApiPublicSettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
